### ISSUE TITLE
AttributeError: type object 'Collection' has no attribute '_undoReview'

### ISSUE THREAD

**Issue by ghost** [mass-immersion-approach/MIARetirementAddon#14]
Having this error when launching anki in Manjaro Linux x64. Is it an anki version problem? I'm running the new 2.1.45 beta, and if I can resolve the error by editing the code I'd be glad trying to do it myself :)
```
When loading '⁨Migaku Retirement⁩':
⁨Traceback (most recent call last):
  File "/home/yaoberh/pyenv/lib/python3.9/site-packages/aqt/addons.py", line 217, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1666520655/__init__.py", line 4, in <module>
    from . import  main, migakuMessage
  File "/home/yaoberh/.local/share/Anki2/addons21/1666520655/main.py", line 352, in <module>
    ogUndoReview = _Collection._undoReview
AttributeError: type object 'Collection' has no attribute '_undoReview'
```

**Comment by RawToast** [comment]
Looks like that should be: `_undo_review`

https://github.com/ankitects/anki/blob/a99f6a8514974a3479bec0c2a367ecd4dfaf7504/pylib/anki/collection.py#L954

If you roll Anki back to 2.1.44, it should work without any changes.
